jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 11092003yaN
          POSTGRES_DB: courses_db
        ports:
          - 5432:5432               # <<< ВАЖНО: проброс порта на localhost runner'а
        options: >-
          --health-cmd "pg_isready -U postgres -d courses_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # можешь оставить 3.11, это не влияет на ошибку

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting 20 seconds for PostgreSQL to start..."
          sleep 20

      - name: Run pytest
        env:
          # Можно вообще не задавать, но если хочешь — оставляем такой же, как в main.py
          DATABASE_URL: postgresql+psycopg2://postgres:11092003yaN@localhost:5432/courses_db
        run: |
          pytest -q
